[versions]
kotlin = "2.1.21"
compose = "1.8.2"
agp = "8.2.0"
intellij-platform-plugin = "2.18.1"
changelog = "2.1.0"
intellij-ide = "2025.1"

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform-plugin" }
jetbrainsChangelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
